define([
    'mcomponents/store-element/store-element.component',
    'mcomponents/big-kpi-bar/big-kpi-bar.component',
    'mcomponents/big-kpi/big-kpi.component',
    'mcomponents/main-kpi-bar/main-kpi-bar.component',
    'mcomponents/main-kpi/main-kpi.component',
    'mcomponents/key-people-bar/key-people-bar.component',
    'mcomponents/key-people/key-people.component',
    'mcomponents/selection-item/selection-item.component',
    'mcomponents/selections-menu/selections-menu.component',
    'mcomponents/filters-sidebar/filters-sidebar.component',
    'mcomponents/store-sidebar/store-sidebar.component',
    'mcomponents/sector-buttons/sector-buttons.component',
    'mcomponents/filters-bar/filters-bar.component',
    'mcomponents/colors-map/colors-map.component',
    'mcomponents/spectrum-combo/spectrum-combo.component',
    'mcomponents/spectrum-scatter/spectrum-scatter.component',
], function() {})